### ISSUE TITLE
Carlos Eduardo Brandão Loureiro

### ISSUE THREAD

**Issue by eduardobrandao** [alissonphp/pt-frontend-angular-01#3]
Bom dia, primeiro pedir desculpas por não ter entregue na sexta, se você ja falou com a recrutadora ela veio falando comigo durante todo o periodo, e quando estava só na parte de fazer o link com a API de vocês, minha mãe teve uma crise de dor muito estranha na hora e assim que cheguei no São Domingos descobrir que ela tinha fissurado a bacia, detalhe ela tem 93 anos, mas enfim tive que ficar com ela internada e teve alta somente hoje, poderia até ter feito no final de semana no hospital com ela mas a minha namorada que foi buscar a maquina pra eu tentar finalizar o teste ainda em tempo, ela levou a maquina da add, que é um Mac e eu nem consigo acessar outra coisa que não seja da empresa, daí então queria Novamente agradecer pela oportunidade e pedir desculpas pela não entrega e surgindo uma nova oportunidade.
OBS:. Eu não terminei porque não achei justo usar o problema que tive com a minha mãe e finalizar, se você quiser te mando até onde eu fiz na sexta-feira, o front ta todo pronto, só não fiz o link com a API.

**Comment by alissonphp** [comment]
Fala Eduardo, lamento pela situação com sua mãe e desejo que ela se recupere bem o mais breve possível.
Sobre o teste, estamos rodando mais um processo e o prazo para esse é até a próxima quinta-feira (30 de junho), caso queira fazer uso desse tempo pra concluir o seu, pode ficar à vontade.

**Comment by eduardobrandao** [comment]
Oh Alisson obrigado pela oportunidade, vou usar sim até quinta eu criou uma
nova issue e te mando o link do repositório, mas uma vez valeu mesmo, você
não vai se arrepender...

Em seg., 27 de jun. de 2022 às 14:08, Alisson Gomes <
***@***.***> escreveu:

**Comment by eduardobrandao** [comment]
Bom dia Alisson, primeiro desculpa pelo projeto que mandei, sei que estava
bem abaixo do que posso fazer, mas como tentei te explicar estava meio sem
tempo e daí náo atentei pra alguns detalhes, mas agora estou sabendo que a
vaga ainda estar em aberto queria ver contigo uma nova oportunidade, sei
que já me deu algumas oportunidades, mas agora estou com mas tempo, e
consigo te mandar um projeto bem melhor, se não for possível  eu agradeço
da mesma forma e boa sorte na sua busca.
Desde já agradeço,
Eduardo Brandão...

Em seg., 27 de jun. de 2022 às 14:49, carlos eduardo ***@***.***>
escreveu:
